# Generated by Django 5.1.5 on 2025-01-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aadhar_card', models.CharField(max_length=12, unique=True)),
                ('driver_license_no', models.CharField(max_length=20, unique=True)),
                ('truck_no', models.CharField(max_length=20)),
            ],
        ),
    ]
