# Generated by Django 5.1.5 on 2025-01-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='truck_no',
        ),
        migrations.AddField(
            model_name='driver',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
