# Generated by Django 5.1.5 on 2025-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_app', '0002_remove_driver_truck_no_driver_transporter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='training_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
